# Default values for kube-news chart.

# -- Overwrite the namespace for all resources
namespace: kube-news

replicaCount: 1

image:
  repository: ghcr.io/messiasloiola/kube-news
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Reference to a secret for pulling images from a private registry
imagePullSecrets: []
# - name: my-registry-secret

service:
  type: NodePort
  port: 8080
  nodePort: 30000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- PostgreSQL sub-chart configuration
postgres:
  # -- PostgreSQL image tag
  image:
    repository: postgres
    tag: "13-alpine"
  # -- Database configuration
  db:
    name: kubedevnews
    user: kubedevnews
  # -- Name of the existing secret that contains the database password
  existingSecret: ""

  resources: {}

  # -- Persistence configuration
  persistence:
    enabled: true
    # -- If undefined or blank, a default StorageClass will be used.
    # For RKE2 or other local clusters, you might need to set this to a specific
    # StorageClass name after installing a provisioner like Longhorn.
    # Example: storageClass: "longhorn"
    storageClass: ""
    size: 1Gi
