apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-news.name" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-news.labels" . | nindent 4 }}
data:
  # App-specific config
  DB_HOST: {{ include "kube-news.name" . }}-postgres

  # Postgres-specific config (for the postgres container)
  DB_DATABASE: {{ .Values.postgres.db.name | quote }}
  DB_USERNAME: {{ .Values.postgres.db.user | quote }}
