apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-news.name" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-news.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "kube-news.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
