---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: kube-news
spec:
  encryptedData:
    .dockerconfigjson: AgBYtIp2IM3mHGrExwB38tNj0+t6DL1QbC2rw01tAGLVHiPC0G+C6NuABQkut4iNRMNqUBKgUhccxoO6EX+00hogn0xaP/MCbYpsfrk3qJpqPqlOpW8SCFdmYOhj5PWcn/E+N4o7VAMJM2E3WOkndyCZP4zUZM7EtWNlGnF2WRzLATfKf6v0i9GWy9RquklFmPnURmS2PclHP0YDdOKlMVCYbQz0uqIdcRADcxL7MtJQ+1OvTIltP3yotOeaprM+LwnwEQJxQR+pycbfbLzjf8u17ZKDBvtoqv1u0YrVR7oM8z1NPPk7QnPCiMBGkixgSErWzLn7z7tjqWHviZn4LzFVh6NWMyWx/+vWPsQzWptibxLSKu+awnh70NINZo4CTKHSp7WuG6F4L8rLiwrxkNcZKABzVM+DXOf0l3u7fMLGx5C/5U1ndXhTWgD8xsE2+NMooSQYHyQEH9cPCsFvvLxHfmP9rNJxWUuCbyP1wUGz4Mxvc7AhqVB6SQaz6nWTuFmj/IkOWCoUDTpm+llEzhzK4Blp5+w3FaHg6bs5gmv0vGvho1/KGx7gXX3TpwKFiTL0DL0AFZMz/MLPR18Sgvz16xAnNOeDoISFfMOix8sp0u1Aj5y+Gvr4DValj+/M5SjmfgUvdhWRUoQtFJDxSuUJ4mxUKQgQqErvvW6udUIgui3wSDMfO181CeWPjzTqsZvZCLccxRm+FeNcJhwu7QIY8SIzk8T/ZSQoVuctci7waBBoX2M5k0kecDlD1z2oMHqJi+exs++h4XDXYfaxai05yjp7IV6jIHQ+Fa9i8+GOEsV3kbxY9dgCZsYwEYhqux4FLgY2yfgJp21fZ2LmxuXDRwF3+f2CuKR59a5seRTKao88YFVWpzurNRCPpA5D9tqt5iATDhq1e4wa1K57uZVVUAyE5F2KBO7SvYtajI/xlPrsAx8hK+TtKyE=
  template:
    metadata:
      name: ghcr-secret
      namespace: kube-news
    type: kubernetes.io/dockerconfigjson
