apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-news.name" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-news.labels" . | nindent 4 }}
type: Opaque
data:
  # The key for the postgres container is POSTGRES_PASSWORD
  # If postgres.password is provided in values, it will be used.
  # Otherwise, a random password will be generated. For production/GitOps,
  # it is strongly recommended to provide a password.
  {{- if .Values.postgres.password }}
  DB_PASSWORD: {{ .Values.postgres.password | b64enc }}
  {{- else }}
  DB_PASSWORD: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
