apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-news
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/messiasloiola/kube-news.git
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-news
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
