
apiVersion: v1
kind: Service
metadata:
  name: kube-news
  namespace: kube-news
  labels:
    app: kube-news
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: kube-news
