
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
  namespace: kube-news
  labels:
    app: kube-news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
    spec:
      containers:
        - name: kube-news
          image: ghcr.io/messias-henry/kube-news:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: kube-news-config
            - secretRef:
                name: kube-news-secret
